name: Charlene Burnside
favicon: null
layout_spectrum: 0.9763889920432121
typography_spectrum: 0.5965003021992743
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.054284352576360106
  lightness: 0.9427704578265548
  saturation: 0.1468593266326934
  rhythmicContrast: 0.6636228633578867
purpose: []
